#!/bin/bash

set -eu

LINTJE_VERSION="0.5.0"

mkdir -p $HOME/bin
cache_key=v1-lintje-$LINTJE_VERSION
cache restore $cache_key

# File exists and is executable
if [ -x "$HOME/bin/lintje" ]; then
  echo "Restored Lintje $LINTJE_VERSION from cache"
else
  echo "Downloading Lintje $LINTJE_VERSION"
  curl -L \
    https://github.com/tombruijn/lintje/releases/download/v$LINTJE_VERSION/x86_64-unknown-linux-gnu.tar.gz | \
    tar -xz --directory $HOME/bin
  cache store $cache_key $HOME/bin/lintje
fi

# When force-pushing, the commit range may begin at a commit that does not
# exist. When this happens, check only the commit at the head of the range.
base_commit="$(echo "$SEMAPHORE_GIT_COMMIT_RANGE" | cut -d '.' -f 1)"

if git cat-file -e "$base_commit"; then
  $HOME/bin/lintje "$SEMAPHORE_GIT_COMMIT_RANGE"
else
  head_commit="$(echo "$SEMAPHORE_GIT_COMMIT_RANGE" | cut -d '.' -f 4)"
  $HOME/bin/lintje "$head_commit"
fi
