#!/usr/bin/env sh

version() {
  echo "$@" | awk -F. '{ printf("%d%03d%03d%03d\n", $1,$2,$3,$4); }';
}

if [ $(version $TRAVIS_ELIXIR_VERSION) -ge $(version "1.5.0") ]; then
  mix compile --warnings-as-errors
fi
