#!/usr/bin/env sh

version() {
  echo "$@" | awk -F. '{ printf("%d%03d%03d%03d\n", $1,$2,$3,$4); }';
}

if [ -z "$TRAVIS_ELIXIR_VERSION" ] || [ $(version $TRAVIS_ELIXIR_VERSION) -ge $(version "1.5.0") ]; then
  MIX_ENV=test mix compile --warnings-as-errors
fi

if [ -z "$TRAVIS_ELIXIR_VERSION" ] || [ $(version $TRAVIS_ELIXIR_VERSION) -ge $(version "1.8.0") ]; then
  MIX_ENV=test mix format --dry-run --check-formatted
  MIX_ENV=test mix credo --strict
fi

MIX_ENV=test mix test
MIX_ENV=test_phoenix mix test
make clean && MIX_ENV=test_no_nif mix test
