name: Elixir Phoenix integration CI

on:
  push:
    branches:
    - main
    - develop
  pull_request:
    types:
    - opened
    - reopened
    - synchronize
  schedule:
    - cron: "0 0 * * 1-5"
  workflow_dispatch:

jobs:
  lint_compile:
    runs-on: ubuntu-latest
    env:
      _APPSIGNAL_CI_PHOENIX_VERSION: "~> 1.8"
    steps:
      - name: Set up Erlang and Elixir
        uses: erlef/setup-beam@v1
        with:
          otp-version: 27.x
          elixir-version: latest
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Get dependencies
        run: mix deps.get
      - name: Check for compilation errors
        run: MIX_ENV=test mix compile --warnings-as-errors

  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        elixir:
          - 1.19.x
        otp:
          - 28.x
          - 27.x
          - 26.x
        phoenix:
          - "~> 1.6.0"
          - "~> 1.7.0"
          - "~> 1.8"
        include:
          - elixir: main
            otp: 28.x
            phoenix: "~> 1.8"
          - elixir: latest
            otp: 28.x
            phoenix: "~> 1.8"
          - elixir: 1.18.x
            otp: 27.x
            phoenix: "~> 1.8"
          - elixir: 1.18.x
            otp: 27.x
            phoenix: "~> 1.7.0"
          - elixir: 1.18.x
            otp: 27.x
            phoenix: "~> 1.6.0"
          - elixir: 1.17.x
            otp: 27.x
            phoenix: "~> 1.8"
          - elixir: 1.17.x
            otp: 27.x
            phoenix: "~> 1.7.0"
          - elixir: 1.17.x
            otp: 27.x
            phoenix: "~> 1.6.0"
          - elixir: 1.16.x
            otp: 26.x
            phoenix: "~> 1.8"
          - elixir: 1.16.x
            otp: 26.x
            phoenix: "~> 1.7.0"
          - elixir: 1.16.x
            otp: 26.x
            phoenix: "~> 1.6.0"
          - elixir: 1.15.x
            otp: 26.x
            phoenix: "~> 1.8"
          - elixir: 1.15.x
            otp: 26.x
            phoenix: "~> 1.7.0"
          - elixir: 1.15.x
            otp: 26.x
            phoenix: "~> 1.6.0"
          - elixir: 1.14.x
            otp: 25.x
            phoenix: "~> 1.7.0"
            plug: "~> 1.19.0"
          - elixir: 1.14.x
            otp: 25.x
            phoenix: "~> 1.6.0"
            plug: "~> 1.19.0"
          - elixir: 1.13.x
            otp: 24.x
            phoenix: "~> 1.7.0"
            plug: "~> 1.18.0"
          - elixir: 1.13.x
            otp: 24.x
            phoenix: "~> 1.6.0"
            plug: "~> 1.18.0"
          - elixir: 1.12.x
            otp: 24.x
            phoenix: "~> 1.7.0"
            plug: "~> 1.18.0"
          - elixir: 1.12.x
            otp: 24.x
            phoenix: "~> 1.6.0"
            plug: "~> 1.18.0"

    steps:
      - name: Set up Erlang and Elixir
        uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.otp}}
          elixir-version: ${{matrix.elixir}}
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Get dependencies
        run: mix deps.get
        env:
          _APPSIGNAL_CI_PHOENIX_VERSION: ${{matrix.phoenix}}
          _APPSIGNAL_CI_PLUG_VERSION: ${{matrix.plug}}
      - name: Run tests
        run: mix test
        env:
          _APPSIGNAL_CI_PHOENIX_VERSION: ${{matrix.phoenix}}
          _APPSIGNAL_CI_PLUG_VERSION: ${{matrix.plug}}
