name: Elixir Plug integration CI

on:
  push:
    branches:
    - "main"
    - develop
  pull_request:
    types:
    - opened
    - reopened
    - synchronize
  schedule:
    - cron: "0 0 * * 1-5"

jobs:
  lint_compile:
    runs-on: ubuntu-latest
    env:
      _APPSIGNAL_CI_PLUG_VERSION: "~> 1.18"
    steps:
      - name: Set up Erlang and Elixir
        uses: erlef/setup-beam@v1
        with:
          otp-version: "28"
          elixir-version: "1.19"
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Get dependencies
        run: mix deps.get
      - name: Check for compilation errors
        run: MIX_ENV=test mix compile --warnings-as-errors

  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        elixir:
          - "1.19.5"
        otp:
          - "28"
          - "27"
          - "26"
        plug:
          - "~> 1.19"
          - "~> 1.18.0"
          - "~> 1.17.0"
          - "~> 1.16.0"
          - "~> 1.15.0"
          - "~> 1.14.0"
        include:
          - elixir: "main"
            otp: "28"
            plug: "~> 1.19"
          - elixir: "latest"
            otp: "28"
            plug: "~> 1.19"
          - elixir: "1.18"
            otp: "27"
            plug: "~> 1.19"
          - elixir: "1.18"
            otp: "27"
            plug: "~> 1.18.0"
          - elixir: "1.18"
            otp: "27"
            plug: "~> 1.17.0"
          - elixir: "1.17"
            otp: "27"
            plug: "~> 1.19"
          - elixir: "1.17"
            otp: "27"
            plug: "~> 1.18.0"
          - elixir: "1.17"
            otp: "27"
            plug: "~> 1.17.0"
          - elixir: "1.16"
            otp: "26"
            plug: "~> 1.19"
          - elixir: "1.16"
            otp: "26"
            plug: "~> 1.18.0"
          - elixir: "1.16"
            otp: "26"
            plug: "~> 1.17.0"
          - elixir: "1.15"
            otp: "26"
            plug: "~> 1.19"
          - elixir: "1.15"
            otp: "26"
            plug: "~> 1.18.0"
          - elixir: "1.15"
            otp: "26"
            plug: "~> 1.17.0"
          - elixir: "1.14"
            otp: "25"
            plug: "~> 1.19.0"
          - elixir: "1.14"
            otp: "25"
            plug: "~> 1.18.0"
          - elixir: "1.14"
            otp: "25"
            plug: "~> 1.17.0"
          - elixir: "1.13"
            otp: "24"
            plug: "~> 1.18.0"
          - elixir: "1.13"
            otp: "24"
            plug: "~> 1.17.0"
          - elixir: "1.12"
            otp: "24"
            plug: "~> 1.18.0"
          - elixir: "1.12"
            otp: "24"
            plug: "~> 1.17.0"

    env:
      _APPSIGNAL_CI_PLUG_VERSION: ${{matrix.plug}}
    steps:
      - name: Set up Erlang and Elixir
        uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.otp}}
          elixir-version: ${{matrix.elixir}}
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Get dependencies
        run: mix deps.get
      - name: Run tests
        run: mix test
